server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Suporte a Single Page Application (impede erro 404 em rotas como /login)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Header de cache ideal para arquivos de manifest do PWA e Service Workers
    location /manifest.webmanifest {
        add_header Cache-Control "no-store, no-cache";
    }

    # Evita erros em assets padrão
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|eot|ttf|json)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
