FROM node:20-bullseye
WORKDIR /app
ENV CI=1
ENV EXPO_NO_TELEMETRY=1
COPY package*.json ./
RUN npm ci
COPY . .
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

# Expor porta 80 para padrão EasyPanel (Fake Server) e 8081 para Expo
EXPOSE 80 8081

CMD ["./entrypoint.sh"]
