FROM node:20-bullseye
WORKDIR /app
ENV CI=1
ENV EXPO_NO_TELEMETRY=1
COPY package*.json ./
RUN npm ci
COPY . .
# Expor porta 80 para padrão EasyPanel
EXPOSE 80
CMD ["npx","expo","start","--tunnel","--port","80","--dev-client"]
