export const eventListResponseSchema = {
    description: 'List of events',
    type: 'array',
    items: {
        type: 'object',
        properties: {
            id: { type: 'string' },
            title: { type: 'string' },
            description: { type: 'string', nullable: true },
            price: { type: 'number' },
            maxGuests: { type: 'integer' },
            participantCount: { type: 'integer' },
            eventDate: { type: 'string' },
            endTime: { type: 'string', nullable: true },
            reservationDeadline: { type: 'string', nullable: true },
            location: { type: 'string' },
            city: { type: 'string', nullable: true },
            state: { type: 'string', nullable: true },
            distanceKm: { type: 'number', nullable: true },
            coverImageUrl: { type: 'string', nullable: true },
            eventType: { type: 'string', nullable: true },
            cuisineTypes: { type: 'array', items: { type: 'string' } },
            vibe: { type: 'array', items: { type: 'string' } },
            accessType: { type: 'string' },
            requiresApproval: { type: 'boolean' },
            allowWaitlist: { type: 'boolean' },
            host: {
                type: 'object',
                properties: {
                    id: { type: 'string' },
                    fullName: { type: 'string', nullable: true },
                    username: { type: 'string', nullable: true },
                    avatarUrl: { type: 'string', nullable: true },
                    isSuperhost: { type: 'boolean' },
                },
            },
        },
    },
} as const;
