export enum NotificationType {
    REGISTRATION_APPROVED = 'REGISTRATION_APPROVED',
    REGISTRATION_REJECTED = 'REGISTRATION_REJECTED',
    NEW_REGISTRATION_PENDING = 'NEW_REGISTRATION_PENDING',
    NEW_REGISTRATION_CONFIRMED = 'NEW_REGISTRATION_CONFIRMED',
    EVENT_UPDATE = 'EVENT_UPDATE',
    EVENT_REMINDER = 'EVENT_REMINDER',
    EVENT_CANCELED = 'EVENT_CANCELED',
    NEW_REVIEW = 'NEW_REVIEW',
    PARTICIPANT_CANCELED = 'PARTICIPANT_CANCELED'
}
