export enum NotificationType {
    REGISTRATION_APPROVED = 'REGISTRATION_APPROVED',
    REGISTRATION_REJECTED = 'REGISTRATION_REJECTED',
    NEW_REGISTRATION_PENDING = 'NEW_REGISTRATION_PENDING',
    EVENT_UPDATE = 'EVENT_UPDATE',
    EVENT_REMINDER = 'EVENT_REMINDER'
}
