import {
  Activity,
  Add,
  Bus,
  Car,
  CloudSnow,
  Colorfilter,
  ProfileRemove,
  Routing,
  Wifi,
  AddCircle,
  Alarm,
  ArrowCircleDown,
  ArrowDown2,
  ArrowLeft,
  ArrowRight,
  ArrowUp2,
  Back,
  Briefcase,
  Building,
  Calendar,
  Camera,
  Card,
  ChemicalGlass,
  Clock,
  CloudCross,
  Code,
  CloseCircle,
  Copy,
  Danger,
  DocumentText,
  Edit2,
  EmptyWallet,
  Eye,
  EyeSlash,
  Filter,
  Flag,
  Flash,
  Gallery,
  Global,
  Google,
  Home2,
  InfoCircle,
  Key,
  Location,
  LocationDiscover,
  Logout,
  Lock,
  Map1,
  Menu,
  Message,
  Messages,
  Money,
  More,
  Notification,
  People,
  Pet,
  Profile,
  ProfileCircle,
  ProfileAdd,
  Refresh,
  Reserve,
  ScanBarcode,
  SearchNormal1,
  Send2,
  Setting2,
  Share,
  ShieldTick,
  Star1,
  TickCircle,
  Timer1,
  Trash,
  Unlock,
  Warning2,
  type Icon as IconsaxIcon,
  type IconProps,
} from 'iconsax-react-nativejs';

const ICONS: Record<string, IconsaxIcon> = {
  add: Add,
  'body-outline': Activity,
  'bus-outline': Bus,
  'car-outline': Car,
  'cash-outline': Money,
  'color-filter-outline': Colorfilter,
  'footsteps-outline': Routing,
  'log-out-outline': Logout,
  'paper-plane-outline': Send2,
  'person-remove-outline': ProfileRemove,
  'snow-outline': CloudSnow,
  'wifi-outline': Wifi,
  bell: Notification,
  'checkmark.circle': TickCircle,
  code: Code,
  gear: Setting2,
  'house.fill': Home2,
  'list.bullet': Menu,
  message: Message,
  'mappin.and.ellipse': Location,
  'paperplane.fill': Send2,
  plus: Add,
  'plus.circle': AddCircle,
  'rectangle.portrait.and.arrow.right': Logout,
  'add-circle-outline': AddCircle,
  'alarm-outline': Alarm,
  'alert-circle': Danger,
  'alert-circle-outline': Danger,
  'arrow-back': ArrowLeft,
  'arrow-down-circle-outline': ArrowCircleDown,
  'arrow-forward': ArrowRight,
  'at-outline': Message,
  'ban-outline': Danger,
  'briefcase-outline': Briefcase,
  'bulb-outline': Flash,
  'business-outline': Building,
  calendar: Calendar,
  'calendar-outline': Calendar,
  camera: Camera,
  'camera-outline': Camera,
  card: Card,
  'card-outline': Card,
  'chatbubble-ellipses-outline': Message,
  'chatbubble-outline': Message,
  'chatbubbles-outline': Messages,
  checkmark: TickCircle,
  'checkmark-circle': TickCircle,
  'checkmark-circle-outline': TickCircle,
  'chevron.left': ArrowLeft,
  'chevron.right': ArrowRight,
  'chevron-back': ArrowLeft,
  'chevron-down': ArrowDown2,
  'chevron-forward': ArrowRight,
  'chevron-up': ArrowUp2,
  close: CloseCircle,
  'close-circle': CloseCircle,
  'close-circle-outline': CloseCircle,
  'cloud-offline-outline': CloudCross,
  'copy-outline': Copy,
  'document-text-outline': DocumentText,
  'ellipsis-horizontal': More,
  'ellipsis-vertical': More,
  'eye-off-outline': EyeSlash,
  'eye-outline': Eye,
  'filter-outline': Filter,
  'flag-outline': Flag,
  'flash-outline': Flash,
  'flask-outline': ChemicalGlass,
  'globe-outline': Global,
  google: Google,
  home: Home2,
  'home-outline': Home2,
  'hourglass-outline': Timer1,
  'images-outline': Gallery,
  'info.circle': InfoCircle,
  'information-circle': InfoCircle,
  'information-circle-outline': InfoCircle,
  'key-outline': Key,
  location: Location,
  'location.fill': Location,
  'location-outline': Location,
  'lock-closed': Lock,
  'lock-closed-outline': Lock,
  'lock-open-outline': Unlock,
  magnifyingglass: SearchNormal1,
  map: Map1,
  menu: Menu,
  'menu-outline': Menu,
  navigate: LocationDiscover,
  'navigate-circle-outline': LocationDiscover,
  'navigate-outline': LocationDiscover,
  'notifications-off-outline': Notification,
  'notifications-outline': Notification,
  options: Setting2,
  'paw-outline': Pet,
  pencil: Edit2,
  'pencil-outline': Edit2,
  people: People,
  'people-outline': People,
  person: Profile,
  'person.fill': Profile,
  'person-circle-outline': ProfileCircle,
  'person-add-outline': ProfileAdd,
  'person-outline': Profile,
  pix: Money,
  'qr-code-outline': ScanBarcode,
  'radio-button-off': CloseCircle,
  'radio-button-on': TickCircle,
  refresh: Refresh,
  'refresh-outline': Refresh,
  'restaurant-outline': Reserve,
  'return-down-back-outline': Back,
  'scan-outline': ScanBarcode,
  search: SearchNormal1,
  'search-outline': SearchNormal1,
  send: Send2,
  'settings-outline': Setting2,
  'share-outline': Share,
  'shield-checkmark': ShieldTick,
  'shield-checkmark-outline': ShieldTick,
  star: Star1,
  'star-outline': Star1,
  time: Clock,
  'time-outline': Clock,
  trash: Trash,
  'trash-outline': Trash,
  'wallet-outline': EmptyWallet,
  'warning-outline': Warning2,
};

const FILLED_NAMES = new Set([
  'camera',
  'card',
  'checkmark-circle',
  'home',
  'location',
  'location.fill',
  'navigate',
  'people',
  'person',
  'person.fill',
  'send',
  'star',
  'time',
]);

export type AppIconProps = Omit<IconProps, 'name'> & {
  name: string;
  weight?: string;
};

/**
 * Canonical icon entry point for the app.
 *
 * Legacy Ionicons and SF Symbols names are accepted during the migration, but
 * every icon is rendered by Iconsax on iOS, Android and web.
 */
export function AppIcon({ name, variant, color = '#202124', size = 24, ...props }: AppIconProps) {
  const IconComponent = ICONS[name] ?? InfoCircle;
  const resolvedVariant = variant ?? (FILLED_NAMES.has(name) ? 'Bold' : 'Linear');

  return (
    <IconComponent
      {...props}
      color={color}
      size={size}
      variant={resolvedVariant}
    />
  );
}

export const IconSymbol = AppIcon;
